[project]
name = "07-environment-variables"
version = "0.1.0"
description = "Environment variables demo"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.121.2",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
