[project]
name = "03-bind-mounts"
version = "0.1.0"
description = "Docker bind mounts demo"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.121.2",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
